# Generated by Django 2.2.3 on 2019-07-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatters',
            new_name='DinnerPlatter',
        ),
    ]
