# Generated by Django 2.2.3 on 2019-07-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190731_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='PizzaTypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.PizzaType'),
        ),
    ]
