# Generated by Django 2.2.3 on 2019-07-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190731_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
