# Generated by Django 2.2.3 on 2019-07-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_topping_price'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.CreateModel(
            name='OrderTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('Toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('Subs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('Salads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Salad')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('PizzaTypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.PizzaType')),
            ],
        ),
        migrations.CreateModel(
            name='Orderpizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('pizzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('Pastas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DinnerPlatters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.DinnerPlatter')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='CartTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('Toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='CartSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('Subs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='CartSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('Salads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Salad')),
            ],
        ),
        migrations.CreateModel(
            name='CartPizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('PizzaTypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.PizzaType')),
            ],
        ),
        migrations.CreateModel(
            name='Cartpizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('pizzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='CartPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('Pastas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='CartDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('DinnerPlatters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.DinnerPlatter')),
            ],
        ),
    ]
