# Generated by Django 2.2.3 on 2019-07-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190731_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizzatype',
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='orderpizzatype',
            name='PizzaTypes',
        ),
        migrations.DeleteModel(
            name='CartPizzaType',
        ),
        migrations.DeleteModel(
            name='OrderPizzaType',
        ),
    ]
